version: "3.8"
services:
  mud:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      # Mount source code for live reload during development
